apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metrics.cpupools.intel.com
spec:
  group: cpupools.intel.com
  versions:
    - name: v1draft1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: metrics
    singular: metric
    kind: Metric
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["pools"]
          properties:
            pools:
              description: List of CPU pools, their CPUs, current capacity, and usage.
              type: array
              properties:
                items:
                  properties:
                    poolName:
                      description: CPU pool name.
                      type: string
                    shared:
                      description: CPU pool CPUs, idle/in shared use.
                      type: string
                    exclusive:
                      description: CPU pool CPUs in exclusive use.
                      type: string
                    capacity:
                      description: CPU pool capacity in millicores.
                      type: integer
                    usage:
                      description: CPU pool usage in millicores.
                      type: integer
                  required:
                  - poolName
                  - shared
                  - exclusive
                  - capacity
                  - usage
