/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1draft1

import (
	v1draft1 "github.com/klihub/cpu-policy-plugins-for-kubernetes/pkg/apis/cpupools.intel.com/v1draft1"
	"github.com/klihub/cpu-policy-plugins-for-kubernetes/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type CpupoolsV1draft1Interface interface {
	RESTClient() rest.Interface
	MetricsGetter
}

// CpupoolsV1draft1Client is used to interact with features provided by the cpupools.intel.com group.
type CpupoolsV1draft1Client struct {
	restClient rest.Interface
}

func (c *CpupoolsV1draft1Client) Metrics(namespace string) MetricInterface {
	return newMetrics(c, namespace)
}

// NewForConfig creates a new CpupoolsV1draft1Client for the given config.
func NewForConfig(c *rest.Config) (*CpupoolsV1draft1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CpupoolsV1draft1Client{client}, nil
}

// NewForConfigOrDie creates a new CpupoolsV1draft1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CpupoolsV1draft1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CpupoolsV1draft1Client for the given RESTClient.
func New(c rest.Interface) *CpupoolsV1draft1Client {
	return &CpupoolsV1draft1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1draft1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CpupoolsV1draft1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
